name = "World"

[[scene]]
model_file = "ampel_mit_mast_oben.obj"
name = "Ampel 1"
id = "a0c49f2b-5e48-48ee-85a2-86a88900617f"
rotation = [0.0, 0.0, 0.0]
position = [15.0, 7.0, -11.0]

[[scene]]
model_file = "ampel_mit_mast_oben.obj"
name = "Ampel 2"
id = "5a49699e-b09d-46bd-bafb-0463fcef5054"
rotation = [0.0, 90.0, 0.0]
position = [-10.0, 7.0, -14.0]

[[scene]]
model_file = "ampel_mit_mast_oben.obj"
name = "Ampel 3"
id = "2be7a064-9ee4-4097-9797-d6d693595b3c"
rotation = [0.0, 180.0, 0.0]
position = [-15.0, 7.0, 11.0]

[[scene]]
model_file = "ampel_mit_mast_oben.obj"
name = "Ampel 4"
id = "c67f737a-b2ad-43ad-ad21-99c87735a141"
rotation = [0.0, 270.0, 0.0]
position = [11.0, 7.0, 16.0]

[[scene]]
model_file = "road.obj"
name = "Straße 1"
id = "1f0aa52f-e369-4d4d-8a02-2c5601dbc18e"
rotation = [0.0, 90.0, 0.0]
position = [45.5, 0.0, 0.0]

[[scene]]
model_file = "road.obj"
name = "Straße 2"
id = "ce57b466-c704-4454-b0a1-f3a2255b1970"
rotation = [0.0, 180.0, 0.0]
position = [0.0, 0.0, -45.5]

[[scene]]
model_file = "road.obj"
name = "Straße 3"
id = "066ca82e-2af1-4125-bc08-58aca5ef0c3a"
rotation = [0.0, 270.0, 0.0]
position = [-45.5, 0.0, 0.0]

[[scene]]
model_file = "road.obj"
name = "Straße 4"
id = "208d67d6-e6f1-4e8d-936d-6d69ba73e5dc"
rotation = [0.0, 0.0, 0.0]
position = [0.0, 0.0, 45.5]

[[scene]]
model_file = "road_centerpiece.obj"
name = "Kreuzung"
id = "97291384-ae49-4215-99f7-30fe500bd2fd"
rotation = [0.0, 0.0, 0.0]
position = [0.0, -0.1, 0.0]
